version: 2
models:
  - name: int_contacts
    description: RDS + Hubspot contact information
    columns:
      - name: phone
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
                regex: '^\(\d{3}\) \d{3}-\d{4}$'
                row_condition: "phone is not null"