version: 2
sources:
  - name: postgres
    database: northwinds
    schema: public
    tables:
      - name: customers
      - name: suppliers
      - name: shippers
      - name: categories

  # AWS RDS
  - name: rds
    database: northwinds
    schema: public
    tables:
      - name: customers
      - name: suppliers
      - name: shippers
      - name: categories

    